[terminal]
[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[window]
opacity = 0.95

[font]
normal       = { family = "Hack Nerd Font", style = "Regular" }
bold         = { family = "Hack Nerd Font", style = "Bold" }
italic       = { family = "Hack Nerd Font", style = "Italic" }
bold_italic  = { family = "Hack Nerd Font", style = "Bold Italic" }
size         = 14

[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001b[1;5C"

[[keyboard.bindings]]
key = "Up"
mods = "Control"
chars = "\u001b[1;5A"

[[keyboard.bindings]]
key = "Down"
mods = "Control"
chars = "\u001b[1;5B"
